### ISSUE TITLE
Adding claims providers via metadata

### ISSUE THREAD

**Issue by betner** [fedtools/adfstoolkit#34]
I'm currently testing the toolkit and I'm having trouble with claims providers in the federation.
My ADFS server is configured as an IdP proxy so I want to add the existing claims providers in the federation and make some of them available to my SP.
The toolkit parses the metadata file and automatically adds the relying parties in the federation but not the claims providers.

Does the toolkit support using AFDS as an IdP proxy and should the claims providers in a federation be added automatically just as the relying parties are?

Thanks!

**Comment by teamktown** [comment]
Hi @betner and  thank you for your request through issue tracker.

No, ADFSToolkit does not support loading of IdP entities -- only relying Parties (SPs) at this time.
A very old (6+ yrs) one that claims what you want to do may be: https://archive.codeplex.com/?p=sila (warning: extremely old and am not sure it truly satisfies everything like validating the aggregate etc. You will likely need to hand edit it to your liking)

ADFSToolkit filters on the SPSSODescriptor element  and starts the journey from the main function in Processes-ADFSTkRelyingPartyTrust.ps1. The IDPSSODescriptor element is skipped/ignored and doesn't  have any code that handles all the elements of an IdP to place it in the ADFS environment. 

An alternative approach for you would be to use a SAML proxy in front of your ADFS proxy environment and have one relying party in ADFS. At this point you ask yourself why do the proxy in front of ADFS and NOT the service itself? 
The usual answer is: because I may have more services to add and only want one endpoint in the federation.

If you have only one SP/RP and don't need ADFS functionality, proxy the actual app instead of using ADFS in front of it. 

Regardless of pathway in the proxy model  means  an additional component in the mix but it simplifies things to a single IdP  (the proxy that handles multi-lateral trust). Solutions besides ADFS+SILA are: Shibboleth IdP v4 as a SAML proxy, SimpleSAMLPHP as a proxy , and SATOSA which specializes in proxying. These solutions have various degrees of complexity involved of course.  An additional consideration is the discovery process for the end user regardless of pathway and is important for a solution but out of scope of a proxy. 

Hope this helps and will leave it open for a bit until closing  it. Feel free to close with a reply  to this.  

Thanks!
Chris @teamktown

**Comment by betner** [comment]
Thank you so much for the answer it really helps alot!

Regards,
Steve
